services:
  - type: web
    name: smart-liquidity-engine
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:create_app()
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: FLASK_DEBUG
        value: false
